README.md

Conda isn't "the Anaconda package manager" but an [independent OSS project governed by the conda organization and governance policy](https://github.com/conda/governance) distributed in a number of conda distributions.

Fix for conda listing in README.

---

src/api.ts
src/features/envCommands.ts
src/features/views/envManagersView.ts
src/features/views/treeViewItems.ts
src/internal.api.ts
src/managers/conda/condaUtils.ts

Closes https://github.com/microsoft/vscode-python-environments/issues/95

Adds group feature environment manager UI

---

src/managers/builtin/venvUtils.ts

Closes https://github.com/microsoft/vscode-python-environments/issues/106
Closes https://github.com/microsoft/vscode-python-environments/issues/107
Closes https://github.com/microsoft/vscode-python-environments/issues/50

Better handling for venv activations

---

src/managers/conda/condaUtils.ts

Closes https://github.com/microsoft/vscode-python-environments/issues/103

Quote `conda env remove` arguments when using full path

---

src/managers/conda/condaUtils.ts

Support using tilded (~) path for `condaPath` setting.

Untildify conda path from settings

---

package.json
package.nls.json
src/extension.ts
src/features/envCommands.ts

Closes https://github.com/microsoft/vscode-python-environments/issues/59

Adds uninstall button on packages

---

src/managers/conda/condaUtils.ts

Moved quoting conda arguments to `runConda` to systematically handle paths with spaces (related to https://github.com/microsoft/vscode-python-environments/pull/113)

Quote arguments systematically when calling conda

---

src/features/terminal/activateMenuButton.ts
src/features/terminal/terminalManager.ts
src/features/terminal/utils.ts

Fixes https://github.com/microsoft/vscode-python-environments/issues/130
For https://github.com/microsoft/vscode-python-environments/issues/27

Ensure activate button is not shown on task terminals

---

src/common/utils/unsafeEntries.ts
src/features/common/shellDetector.ts
src/managers/builtin/venvUtils.ts

Fixes #138
This adds shell activation for
- gitbash
- wsl
- ksh
- tcshell
- xonsh
- nushell
and fixes shell activation for C shell.
it also makes sure that it’s impossible to add a terminal to the enum without also adding shell activation/deactivation commands by using a `Record` type that needs to be exhaustive.

Handle all shells’ de/activation

---

src/common/pickers/projects.ts
src/features/envCommands.ts
src/test/copilotTools.unit.test.ts
src/test/features/envCommands.unit.test.ts

Fixes https://github.com/microsoft/vscode-python-environments/issues/140

Handle venv creation when running in no-workspace case

---

package.json

as we determine the best use of this tool, do not expose it as reference-able in copilot chat.

remove ability to reference get_packages from prompting

---

package.json
src/features/common/shellDetector.ts
src/vscode.proposed.terminalShellType.d.ts

@anthonykim1 The VSCode shell type is missing following types: `tcshell`, `wsl`, `xonsh`

Adopt Terminal Shell Type API from VSCode with legacy fallback

---

package.json
src/features/terminal/terminalManager.ts
src/vscode.proposed.terminalShellEnv.d.ts

This was a very easy API to consume.

Use Terminal Shell Env API to detect activations

---

package.json
package.nls.json
src/common/env.apis.ts
src/extension.ts
src/features/envCommands.ts
src/test/features/commands/copyPathToClipboard.unit.test.ts

Closes https://github.com/microsoft/vscode-python-environments/issues/166

feat: Add copy path to Project and Environments

---

src/features/common/shellDetector.ts

fixes https://github.com/microsoft/vscode-python-environments/issues/159
We need to wrap the API in a try-catch block to handle any potential errors that might occur as it is currently being worked on.

fix: wrap the experimental shell type API with try-catch

---

src/common/utils/unsafeEntries.ts
src/features/common/shellDetector.ts
src/managers/builtin/venvUtils.ts
src/managers/conda/condaUtils.ts
src/test/features/common/shellDetector.unit.test.ts

fixes https://github.com/microsoft/vscode-python-environments/issues/173

fix: use '/' delimiter on windows when using gitbash.

---

README.md

Full diff:
```diff
-https://github.com/microsoft/vscode-python-environments/blob/main/src/examples/README.md
+https://github.com/microsoft/vscode-python-environments/blob/main/examples/README.md
```

Fix broken link to `examples` in `README.md`

---

package.json

fixes https://github.com/microsoft/vscode-python-environments/issues/208
fix for this:

fix: cannot register tools starting with `vscode_`

---

src/common/localize.ts
src/managers/builtin/pipUtils.ts
src/managers/conda/condaUtils.ts

closes: https://github.com/microsoft/vscode-python-environments/issues/212

feat: add option to skip package installation in `venv` and `conda` installers

---

package.json

bug: hide duplicate command from the command palette

---

src/managers/builtin/pipManager.ts
src/managers/builtin/pipUtils.ts
src/managers/common/pickers.ts

closes https://github.com/microsoft/vscode-python-environments/issues/224

fix: for venv common packages shows installed packages pre ticked

---

src/common/localize.ts
src/managers/builtin/venvUtils.ts

closes https://github.com/microsoft/vscode-python-environments/issues/258
/cc @cwebster-99 Need your input on the text

feat: add "Quick Create" option for venvs

---

src/features/common/shellDetector.ts
src/managers/builtin/venvUtils.ts
src/managers/conda/condaUtils.ts

fixes https://github.com/microsoft/vscode-python-environments/issues/282

fix: ensure script casing match for activations

---

examples/sample1/src/api.ts
examples/sample1/src/sampleEnvManager.ts
src/api.ts
src/common/localize.ts
src/common/pickers/environments.ts
src/common/pickers/managers.ts
src/features/envCommands.ts
src/features/pythonApi.ts
src/internal.api.ts
src/managers/builtin/venvManager.ts
src/managers/builtin/venvUtils.ts
src/managers/conda/condaEnvManager.ts
src/managers/conda/condaUtils.ts
src/test/features/envCommands.unit.test.ts

closes https://github.com/microsoft/vscode-python-environments/issues/273

feat: Add support for Quick Create

---

src/api.ts

The descriptions seem to be leftovers from #279.

fix: clarify that `showSkipOption` also applies to uninstallations

---

src/common/utils/frameUtils.ts
src/features/envManagers.ts

Fixes https://github.com/microsoft/vscode-python-environments/issues/223

fix: id generation for env and pkg managers

---

src/common/utils/pathUtils.ts
src/features/pythonApi.ts

fixes https://github.com/microsoft/vscode-python-environments/issues/278

add handling for notebook-cells as inputs to API

---

src/extension.ts
src/features/creators/autoFindProjects.ts
src/features/creators/existingProjects.ts
src/features/envCommands.ts

fixes https://github.com/microsoft/vscode-python-environments/issues/305

update for existing project creation

---

src/managers/builtin/main.ts
src/managers/builtin/pipUtils.ts

fixes: https://github.com/microsoft/vscode-python-environments/issues/57

fix: detect terminal `pip installs` and refresh ui

---

README.md
src/common/pickers/managers.ts
src/features/envCommands.ts

fixes: https://github.com/microsoft/vscode-python-environments/issues/321
The following fields are supported when using `python-envs.createAny` command:
```
/**
* Default `false`. If `true` the creation provider should show back button when showing QuickPick or QuickInput.
*/
showBackButton?: boolean;
/**
* Default `true`. If `true`, the environment after creation will be selected.
*/
selectEnvironment?: boolean;
```

fix: show back button with create environment

---

src/api.ts
src/features/creators/existingProjects.ts
src/features/envCommands.ts

update the API surface to change return type of the project creator

update return type of project create

---

src/features/terminal/shells/bash/bashStartup.ts
src/features/terminal/shells/fish/fishStartup.ts

Standardize the display names of various shell providers to use lowercase for consistency.
Fixes https://github.com/microsoft/vscode-python-environments/issues/230

fix: inconsistent shell name display

---

src/features/projectManager.ts

fixes https://github.com/microsoft/vscode-python-environments/issues/355
regression occurred since now settings edits were made for every project add where only project settings that differ from the default need to be added to the settings

 ignore setting updates on default project selection

---

package.json

fixes https://github.com/microsoft/vscode-python-environments/issues/345
fixes https://github.com/microsoft/vscode-python-environments/issues/352

edits to get environment tool descriptions

---

src/managers/builtin/main.ts
src/managers/builtin/venvUtils.ts

fixes: https://github.com/microsoft/vscode-python-environments/issues/383
The fix is to trigger FS event on `activate` file creation. This makes sure that we have the right files available for the environment.

fix: resolve on filesystem trigger does not use correct `activate`

---

docs/projects-api-reference.md
src/features/projectManager.ts

added a doc explaining how the project technical design works
add comments and docstrings for clarity

updates to project manager docs and comments

---

src/features/creators/autoFindProjects.ts

fixes https://github.com/microsoft/vscode-python-environments/issues/398

bug fixes autoFindProjects

---

src/features/projectManager.ts
src/features/settings/settingHelpers.ts
src/internal.api.ts

fixes https://github.com/microsoft/vscode-python-environments/issues/400

add workspace attribute to project setting

---

README.md
src/features/terminal/shells/cmd/cmdStartup.ts
src/features/terminal/shells/common/shellUtils.ts

Enhance the shell startup process by refining the command handling and updating the documentation for better clarity. Adjustments ensure proper execution in specific environments.

Improve shell startup documentation and logic

---

src/extension.ts
src/features/creators/creationHelpers.ts
src/features/creators/newPackageProject.ts
src/features/creators/newScriptProject.ts
src/features/creators/templates/copilot-instructions-text/script-copilot-instructions.md
src/features/creators/templates/new723ScriptTemplate/script.py

fixes https://github.com/microsoft/vscode-python-environments/issues/393

create project with 723 style script

---

src/managers/builtin/sysPythonManager.ts

fixes https://github.com/microsoft/vscode-python-environments/issues/413

remove duplicate exec in dropdown selector

---

src/features/envCommands.ts

improves the problem faced here: https://github.com/microsoft/vscode-python-environments/issues/470 but I think ultimately we should determine a more comprehensive flow

feat: add button from no workspace open in new project flow

---

src/common/pickers/managers.ts
src/features/envCommands.ts

fixes https://github.com/microsoft/vscode-python-environments/issues/465

feat: add workspace folder selection for project creation

---

src/features/envCommands.ts
src/features/envManagers.ts
src/internal.api.ts

fixes https://github.com/microsoft/vscode-python-environments/issues/507
introduce `setEnvironmentsIfUnset` so that newer environments when created do not override existing settings

add check for already set project environments and add documentation

---

src/managers/poetry/main.ts
src/managers/poetry/poetryUtils.ts

fixes https://github.com/microsoft/vscode-python-environments/issues/503

remove poetry warning popup

---

src/common/telemetry/constants.ts

We are sending the following event locally `ms-python.vscode-python-envs/PACKAGE_MANAGEMENT` but this is not classified in our GDPR tool due to the mismatched GDPR tag. 
The following is cleared in the GDPR tool based on the GDPR tag 
I think this small change will suffice to align the two

Fixing GDPR telemetry naming for package management

---

src/features/creators/newScriptProject.ts

fixes https://github.com/microsoft/vscode-python-environments/issues/579

remove pep 723 reference from create new flow

---

src/features/views/pythonStatusBar.ts
src/features/views/revealHandler.ts

change hover on tooltip to show full env path

---

src/managers/builtin/venvManager.ts

fixes https://github.com/microsoft/vscode-python-environments/issues/491

fixes recursive venv assignment and incorrect multiroot result

---

src/features/terminal/runInTerminal.ts

Resolves https://github.com/microsoft/vscode-python-environments/issues/649

Attach & for shell integration enabled pwsh case

---

src/managers/builtin/venvManager.ts

fixes https://github.com/microsoft/vscode-python-environments/issues/619
since environmentPath for an environment can be "Path to the python binary or environment folder." need to update code to support if the path is directly to a python binary. If so get the parent, parent of the binary to get the venv folder

bug: fix gitignore add for more scenarios

---

src/features/execution/execUtils.ts
src/features/execution/runAsTask.ts

might fix https://github.com/microsoft/vscode-python-environments/issues/642, waiting on clarification

add quoting logic in runAsTask

---

src/managers/builtin/pipListUtils.ts
src/test/managers/builtin/pipListUtils.unit.test.ts
src/test/managers/builtin/piplist3.actual.txt
src/test/managers/builtin/piplist3.expected.json

Addressing bug #697.
When parsing the output of pip list for packages, two checks were added. First, does the line contain exactly two space-separated keywords? The assumption being we will exactly see "[package name] [package version]" in a valid package list. Secondly, it uses the [regex in the PEP 440 docs](https://peps.python.org/pep-0440/#appendix-b-parsing-version-strings-with-regular-expressions) to verify a valid pip version. Adding these checks will help ensure we only parse valid packages and don't pick up any other information, such as warning messages. Lastly, added a unit test for the situation described in the bug.

bug fix: Stricter pip list Package Parsing

---

src/features/terminal/shellStartupSetupHandlers.ts
src/features/terminal/shells/common/shellUtils.ts
src/features/terminal/terminalManager.ts

Resolves: https://github.com/microsoft/vscode/issues/262213

Fix to prevent multiple shell startup prompts

---

.vscodeignore

When running an extension test using VS Code test explorer extension, the installed Python env extension gets picked up as well due to the presence of this file

Remove .vscode-test.mjs from bundled extension

---

src/common/localize.ts
src/managers/pipenv/main.ts
src/managers/pipenv/pipenvManager.ts
src/managers/pipenv/pipenvUtils.ts

scaffolding for pipenv as an env manager

initial scaffolding

---

src/managers/common/nativePythonFinder.ts

wrong:
correct:
here you see the pipenv env shows up correctly

fix venvFolder injection in search path for nativeFinder

---

src/features/execution/runInBackground.ts

fixes https://github.com/microsoft/vscode-python/issues/25448

fix quoting for runInBackground

---

src/managers/builtin/venvUtils.ts

fixes https://github.com/microsoft/vscode-python-environments/issues/484

fix: normalize path for UI display when removing virtual environments

---

src/features/terminal/shells/bash/bashStartup.ts
src/features/terminal/terminalManager.ts

Resolves: https://github.com/microsoft/vscode-python-environments/issues/865 
If user modifies already existing shell profile script needed for shell startup, they get stuck into not activating state because they still have auto activation guard, which blocks shell integration from core from activating.
This also means because they have wrong env var in profile script, it won't activate there either.
We should better track this, and properly clean up profile script when relying on shell integration for activation. 
/cc @karthiknadig

Fix where activation goes missing after user modifying rc scripts

---

src/features/terminal/terminalEnvVarInjector.ts

fixes https://github.com/microsoft/vscode-python-environments/issues/883

fix env var clearing

---

src/features/execution/execUtils.ts

fixes https://github.com/microsoft/vscode-python-environments/issues/876

Fix quoting logic to escape special characters in exec path

---

.github/instructions/generic.instructions.md
eslint.config.mjs
src/test/features/terminalEnvVarInjectorBasic.unit.test.ts

fixes https://github.com/microsoft/vscode-python-environments/issues/881

fix as-any linting warnings

---

.github/instructions/generic.instructions.md
eslint.config.mjs
src/test/features/terminalEnvVarInjectorBasic.unit.test.ts

Reverts microsoft/vscode-python-environments#891
the tests weren't passing and I didn't realize it would merge it in without that criteria met

Revert "fix as-any linting warnings"

---

src/features/terminal/utils.ts
src/test/features/terminal/utils.unit.test.ts
src/test/mocks/mockDocument.ts

fixes https://github.com/microsoft/vscode-python-environments/issues/894

Fix bug with getAutoActivationType

---

src/common/pickers/managers.ts
src/extension.ts
src/helpers.ts
src/managers/builtin/venvStepBasedFlow.ts
src/managers/builtin/venvUtils.ts
src/managers/conda/condaStepBasedFlow.ts
src/managers/conda/condaUtils.ts

fixes https://github.com/microsoft/vscode-python-environments/issues/523 and https://github.com/microsoft/vscode-python-environments/issues/855

feat: add back button to all necessary flows in UI
