src/api.ts, src/features/envManagers.ts, src/managers/builtin/cache.ts, src/managers/builtin/sysPythonManager.ts, src/managers/builtin/venvManager.ts, src/managers/builtin/venvUtils.ts, src/managers/conda/condaEnvManager.ts, src/managers/conda/condaUtils.ts
=> Fix bug with setting environments for multi-root workspaces

src/managers/builtin/venvUtils.ts
For https://github.com/microsoft/vscode-python-environments/issues/109
=> Ensure `pwsh` (powershell Core) use the right activation script

src/common/telemetry/constants.ts
@karthiknadig Joh made a nice eslint rule for this which may make be useful to adopt to avoid these cases
https://github.com/microsoft/vscode-copilot/blob/main/.eslintplugin/no-bad-gdpr-comment.ts
=> Fix telemetry properties

src/features/terminal/terminalManager.ts
Fixes https://github.com/microsoft/vscode-python-environments/issues/125
=> Fix bug with updating activation state for terminal activate button

src/managers/conda/condaUtils.ts, src/managers/conda/main.ts
Fixes https://github.com/microsoft/vscode-python-environments/issues/132
=> Include native finder conda when searching

src/common/telemetry/constants.ts
Addressing unmatched GDPR names
=> Fix GDPR tags

package-lock.json, package.json
Fixes https://github.com/microsoft/vscode-python-environments/issues/159
=> Pin engine version to enable proposed features

src/features/views/treeViewItems.ts, src/managers/builtin/venvManager.ts
fixes https://github.com/microsoft/vscode-python-environments/issues/167
=> Move description of env managers to tooltip

src/extension.ts
fixes https://github.com/microsoft/vscode-python-environments/issues/210
=> fix: cannot read properties of undefined reading 'value'

src/api.ts, src/common/window.apis.ts, src/features/envCommands.ts, src/managers/builtin/pipManager.ts, src/managers/builtin/pipUtils.ts, src/managers/builtin/venvUtils.ts, src/managers/conda/condaPackageManager.ts, src/managers/conda/condaUtils.ts
* ensure skip install is only shown when relevant 
* ensure delete env message is modal
fixes https://github.com/microsoft/vscode-python-environments/issues/220
=> fix: UX when installing packages

src/common/telemetry/constants.ts, src/managers/builtin/venvUtils.ts
closes https://github.com/microsoft/vscode-python-environments/issues/268
=> feat: telemetry when using quick create

src/common/utils/frameUtils.ts, src/common/utils/pathUtils.ts
fixes: https://github.com/microsoft/vscode-python-environments/issues/223
fixes: https://github.com/microsoft/vscode-python-environments/issues/260
fixes: https://github.com/microsoft/vscode-python-environments/issues/261
=> fix: bug with `filePath` when finding calling extension

src/common/pickers/managers.ts
Fixes https://github.com/microsoft/vscode-python/issues/25022
=> fix: quick create does not show up when there only one provider

src/managers/builtin/pipUtils.ts, src/managers/builtin/utils.ts, src/test/managers/builtin/installArgs.unit.test.ts
For https://github.com/microsoft/vscode-python-environments/issues/369
=> fix: bad install step when attempting editable install

src/managers/builtin/sysPythonManager.ts
left a comment and forgot to remove this before
=> remove un-intended comment

src/managers/pyenv/main.ts, src/managers/pyenv/pyenvUtils.ts
=> fix: for `pyenv` spinning forever and crashes

src/extension.ts
=> remove unused imports for environment tools

src/managers/builtin/venvManager.ts, src/managers/builtin/venvUtils.ts
fixes https://github.com/microsoft/vscode-python-environments/issues/505
=> bug: support user aborting env deletion via modal venv

src/managers/builtin/utils.ts
=> remove nested globes in envs explorer

examples/sample1/src/api.ts, src/api.ts, src/features/views/treeViewItems.ts
fixes https://github.com/microsoft/vscode-python-environments/issues/168
=> Remove project icon

src/features/projectManager.ts
fixes https://github.com/microsoft/vscode-python-environments/issues/542
=> remove stray console log

README.md
Update readme to include Create Project from Template
=> Update readme for create project

src/common/pickers/environments.ts
fixes https://github.com/microsoft/vscode-python-environments/issues/485
=> bug fix to make quick create function from project panel select env

src/managers/builtin/venvManager.ts
fixes https://github.com/microsoft/vscode-python-environments/issues/553
=> feat: open parent folder of venv after creation

src/managers/builtin/venvManager.ts
previous PR was incorrect, this one correctly handles https://github.com/microsoft/vscode-python-environments/issues/553
=> fix reveal for venv creation

src/features/creators/newScriptProject.ts, src/features/envCommands.ts
fixes https://github.com/microsoft/vscode-python-environments/issues/478
=> move open script to creator function

src/features/terminal/shells/bash/bashConstants.ts, src/features/terminal/shells/bash/bashStartup.ts, src/features/terminal/shells/fish/fishConstants.ts, src/features/terminal/shells/fish/fishStartup.ts, src/features/terminal/shells/pwsh/pwshConstants.ts, src/features/terminal/shells/pwsh/pwshStartup.ts
=> fix: add guard for shell script re-run

src/features/terminal/shells/bash/bashStartup.ts, src/features/terminal/shells/fish/fishStartup.ts, src/features/terminal/shells/pwsh/pwshStartup.ts
Resolves: https://github.com/microsoft/vscode-python-environments/issues/726 
Coming from https://github.com/microsoft/vscode-python-environments/pull/717 
/cc @karthiknadig
=> Remove debris if shell integration is available

src/managers/pipenv/pipenvUtils.ts
fixes https://github.com/microsoft/vscode-python-environments/issues/824
=> fix: improve environment display name for pipenv

src/features/terminal/shells/bash/bashStartup.ts, src/features/terminal/shells/common/shellUtils.ts, src/features/terminal/shells/fish/fishStartup.ts, src/features/terminal/shells/pwsh/pwshStartup.ts, src/features/terminal/terminalManager.ts
Resolves: https://github.com/microsoft/vscode-python-environments/issues/865
=> Fix wsl not activating properly. 
